### PR TITLE
translations: Fix 'fuzzy' warnings:

### PR DESCRIPTION
**Pull request by sc0w**
Fixes the warnings:
```
warning: PO file header fuzzy
warning: older versions of msgfmt will give an error on this
```

I am not sure if we need fuzzy, I don't know what means and why is there.

...and I don't know if the job can be done here, or it must be done at transifex.

### CODE REVIEW

**Comment by raveit65** [comment]
Hopefully he warnings will be gone after the first pull from transifex?

**Comment by sc0w** [comment]
I don't know, seems we must to remove all these lines to avoid the warnings, I don't know if it can be done here or at transifex.

**Comment by raveit65** [comment]
> I don't know if it can be done here or at transifex.

You can test this. Copy this branch and do a `tx pull -af`.
Does the warnings come back?

**Comment by sc0w** [comment]
I did it, and "`#, fuzzy`" returns again in all the languages

**Comment by raveit65** [comment]
Ok, maybe updating the transifex resource flie (.pot) after gettext commits is needed first.
@rbuj @yetist @monsta 
Any ideas?

**Comment by yetist** [comment]
If transifex does not automatically add fuzzy, push new pot into transifex should work.

**Comment by raveit65** [comment]
I just updated resource for transifex.
https://github.com/mate-desktop/libmatemixer/commit/fcffc0f2c082b8a5532872d4785f4e67d8e2d8b7

**Comment by raveit65** [comment]
And i removed `fuzzy` from resource file.
https://github.com/mate-desktop/libmatemixer/commit/ede5f173efa40ab7477df1eb92ab1294a3f3438a
We need to wait for auto-update from transifex , it happens 2 times a day.
Than we can do a test pull from transifex again and we know if this comes from transifex or it was already in our repo.

**Comment by sc0w** [comment]
now it works!

with `tx pull -af` the lines `#, fuzzy` are removed

little question, @raveit65 which command do you use to make "sync with transifex" commits? `tx pull -af` ? (I am newbie using transifex command line)

**Comment by raveit65** [comment]
@sc0w 
yes, for "sync with transifex" commits i use `tx pull -af` (all languages)
For one a specific language you can use `tx  pull -l de` for example.

OK, that means we need to upload new resource files without `#, fuzzy` lines.
I am so happy that this works and not becomes a drama :)

**Comment by sc0w** [comment]
Sadly, when we do ./makepot again, the fuzzy line comes back

See https://github.com/mate-desktop/libmatemixer/pull/21

**Pull request closed without merging**
