### PR TITLE
libmatemixer: avoid deprecated g_type_class_add_private

### PR DESCRIPTION
**Pull request by yetist**

### CODE REVIEW

**Review by raveit65 — APPROVED** [review]
Builds an runs fine.
Currently i am using alsa because of poor pulseaudio support of my Creative Soundblaster Z.
Alsa support in our mixing gui is very limited, and you can't test much.
Sound, mixer-gui, mixer-applet and OSD controls are running fine.

**Review by lukefromdc — COMMENTED** [review]
This didn't get all of the instances of g_type_class_add_private , but it did build and run without any problems here. I am OK with merging it now or with dealing with the rest prior to merge

**Review by lukefromdc — APPROVED** [review]
Approving as it is a good start. Accidently re-requested Raveit65's review due to slow website response to the mouse, consider this to have TWO APPROVALS, mine and his as of now

**Comment by raveit65** [comment]
> re-requested Raveit65's review due to slow website response to the mouse

I don't know what you mean? 
Which slow website?
Why is a slow website related to PR?

**Comment by lukefromdc** [comment]
It's not related to the PR in any way, its just that with my connection, sometimes when I re-request my own review the response is slow and I click again-only to find that the second click re-requested someone else's review. This PR is good to go on my end and you've already approved it too,. Sorry about the hassle.

**Pull request merged**
