### PR TITLE
Travis CI: enable clang analyzer and cppcheck html reports

### PR DESCRIPTION
**Pull request by sc0w**
`scan-build: No bugs found.`

@yetist maybe you like to add more commits to work with https://libmatemixer.mate-desktop.dev ?

### CODE REVIEW

**Comment by raveit65** [comment]
Hmm, i can't connect with firefox to https://libmatemixer.mate-desktop.dev/ because of a security warning.

**Comment by sc0w** [comment]
@raveit65 by the moment this PR only enables clang analyzer to work in the logs.

> Hmm, i can't connect with firefox to https://libmatemixer.mate-desktop.dev/ because of a security warning.

yes, I think @yetist needs to do something there in the site, and here in PR, and later cppcheck html report can be added too.

**Comment by raveit65** [comment]
I can enable the site in settings but gh-pages branch is missing.
libmate-mixer-gh-pages-1

libmate-mixer-gh-pages-2

Normal it looks like this, eg mate-desktop
mate-desktop-gh-pages

No idea what is missing.

**Comment by sc0w** [comment]
in other repositories, `CNAME` file is inside `gh-pages` branch

I don't know how to make the branch, @yetist please, can you help us?

**Comment by sc0w** [comment]
I did the work, now https://libmatemixer.mate-desktop.dev is working

@raveit65 I think is safe to remove CNAME in master

**Comment by raveit65** [comment]
Ok, i reverted the cname commit and added the custom page again to create the cname commit at gh-pages branch.

**Review by raveit65 — APPROVED** [review]
LGTM.
preview is working.

**Pull request merged**
