### PR TITLE
Use WARN_CFLAGS which are only set with --enable-compiler-warnings

### PR DESCRIPTION
**Pull request by rbuj**
It removes --enable-more-warnings, since it is recommended to use
--enable-compile-warnings=maximum

### CODE REVIEW

**Comment by raveit65** [comment]
Travis config needs update to use latest mate-common and autoconf-archive, or not?

**Review by raveit65 — CHANGES_REQUESTED** [review]
Travis (Ci) needs updating to use latest mate-common and actual dependencies.

**Comment by raveit65** [comment]
I add mate-common from master, autoconf-archive dependency and set compile warnings to maximum,
but build failed always in another branch for testing.
No idea why.
https://github.com/mate-desktop/libmatemixer/commits/warnings-travis

**Comment by raveit65** [comment]
@rbuj
Do we need mate-common from master and autoconf-archive as build dependency here?

**Comment by raveit65** [comment]
@yetist 
We need to switch from 
```
script:
  - ./docker-build --name ${DISTRO} --verbose --config .travis.yml --build autotools
```
to
```
script:
  - ./docker-build --name ${DISTRO} --verbose --config .travis.yml --build scripts
```
?

**Comment by yetist** [comment]
Yes, you are right. If add build_scripts in .travis.yml,  use the second line.

**Comment by raveit65** [comment]
@yetist 
Is moving
```
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     curl -Ls -o debian.sh https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/debian.sh
  -     bash ./debian.sh
  - fi
```
from before_scripts to build_scripts correct?
I have forgotten why we use debian.sh?

**Comment by yetist** [comment]
debian.sh can fix intltool's bug on debian, without the patch, make dist maybe failed.

**Comment by raveit65** [comment]
> debian.sh can fix intltool's bug on debian, without the patch, make dist maybe failed.

I meant in which place it should be? before_scripts or build_script ?

**Comment by rbuj** [comment]
It's a system wide patch, It can be placed in before_scripts.

**Comment by raveit65** [comment]
@rbuj 

> It's a system wide patch, It can be placed in before_scripts.

But why it is in build_scripts :P
https://github.com/mate-desktop/libmatemixer/pull/16/commits/554bcfa9483ea5b7bc25068632fdaed887182754#diff-354f30a63fb0907d4ad57269548329e3R85

And can you please fix this line?
```
script:
  - ./docker-build --name ${DISTRO} --verbose --config .travis.yml --build autotools
```
to
```
script:
  - ./docker-build --name ${DISTRO} --verbose --config .travis.yml --build scripts
```
Otherwise build_scripts won't be used.

**Comment by rbuj** [comment]
@raveit65 done

**Comment by raveit65** [comment]
And now, it's getting weird. I did run in the same issue yesterday with my test branch.
https://travis-ci.org/mate-desktop/libmatemixer/jobs/595268686#L1030
```
libtool:   error: cannot find the library '../../libmatemixer/libmatemixer.la' or unhandled argument '../../libmatemixer/libmatemixer.la'
```

**Comment by yetist** [comment]
debian.sh must run before starting the building, so we can place it in before_scripts or build_scripts.

**Comment by raveit65** [comment]
Ahh,
the `make` command was missing after `./autogen.sh --enable-compile-warnings=maximum` in `build-scripts.

**Review by raveit65 — APPROVED** [review]

**Comment by raveit65** [comment]
Thanks for all.

**Comment by sc0w** [comment]
is possible to build over git master version directly? (mate-common)

I mean, download the latest version with latest commit of master branch, and build it.

**Comment by raveit65** [comment]
mate-common-1.23.3 is nearly latest master, latest commit for release-server isn't needed.
I think we built mate-desktop from master somewhere in travis configs, a while ago.

**Comment by sc0w** [comment]
See https://github.com/mate-desktop/libmatemixer/pull/17

**Pull request merged**
